version: "3.9"
services:
  web:
    build: .
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env.development
    depends_on:
      - db
  db:
    container_name: todo_list_db
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - .env.development

  pgAdmin:
    container_name: todo_list_pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    env_file:
      - .env.development
    depends_on:
      - db
